/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.gyic.claim.ui.control.viewHelper;

import  jxl.*;

import java.io.*;

import  jxl.read.biff.BiffException;
import org.apache.struts.upload.FormFile;

import java.sql.ResultSet;


import com.sinosoft.claim.bl.facade.BLPrpLcompensateFacade;

import com.sinosoft.claim.dto.domain.PrpLcompensateDto;

import com.sinosoft.prpall.blsvr.cb.BLPrpCmainAgri;

import com.sinosoft.sysframework.reference.AppConfig;
import com.sinosoft.sysframework.reference.DBManager;

import com.sinosoft.utility.SysConfig;



/** 
 * MyEclipse Struts
 * Creation date: 10-23-2009
 * 
 * XDoclet definition:
 * @struts.action path="/loadAction" name="loadForm" scope="request" validate="true"
 * @struts.action-forward name="importBasicInfo" path="/importBasicInfo.jsp"
 */

public class AgriCheckPlantingLossViewHelper  {


	public AgriCheckPlantingLossViewHelper(){
	}

	public String CheckPlantingLoss(String strBusinessNo,String strRiskCode)
	{
		BLPrpLcompensateFacade blPrpLcompensateFacade = new BLPrpLcompensateFacade();
		BLPrpCmainAgri blPrpCmainAgri = new BLPrpCmainAgri();

		PrpLcompensateDto prpLcompensateDto;
		String result = "-1";
		String sql    = "";
		String planting31FarmerListFlag = "3147,3141,3140";
		String plantingFarmerListFlag = "3101,3107,3108,3122,3114,3126,3143,3145,3139,3142,3144,3146,3161,3162,3164,3186,3149,3150,3148,3174,3151,3197,3185,3166,3184,3165,3152,3153,3154,3155,3156,3190,3191,3132,3172,3194,3193,3187,3178,3179,3158,3176,3177,3157,3181,3170,31A6";
		//boolean isReopen = UIClaimPlanting31SettleLoadFacade.isReopenCase(registNo, policyNo,nodeType,strBusinessNo);
		//UIClaimPlanting31SettleLoadFacade uiClaimPlanting31SettleLoadFacade = new UIClaimPlanting31SettleLoadFacade();
		if (planting31FarmerListFlag.indexOf(strRiskCode) >-1 || plantingFarmerListFlag.indexOf(strRiskCode) >-1) {
			try {
				//planting31FarmerListFlag = SysConfig.getProperty("PLNATING_31_FARMER_LIST_FLAG","claim");
				prpLcompensateDto = blPrpLcompensateFacade.findByPrimaryKey(strBusinessNo);
				// 去除预赔案件的情况
				if(prpLcompensateDto != null) {
					blPrpCmainAgri.getData(prpLcompensateDto.getPolicyNo());

					if(null!=planting31FarmerListFlag && planting31FarmerListFlag.indexOf(strRiskCode) > -1 )
					{
						sql +=" SELECT COUNT(c.settlelistcode) AS RESULT                                                               ";
						sql +="   FROM PLANTING31SETTLELIST C                                              ";
						sql +="  WHERE C.SETTLELISTCODE = '"+ prpLcompensateDto.getClaimRelationNo()+    "'";
						sql +="    AND NODETYPE = 'compe'                                                  ";
						sql +="    AND EXISTS                                                              ";
						sql +="  (SELECT 1                                                                 ";
						sql +="           FROM PLANTING31POLICYLIST D                                      ";
						sql +=" WHERE D.INUSRELISTCODE = '"+ blPrpCmainAgri.getArr(0).getRelationListNo()+    "'";
						sql +="            AND C.FIDCARD = D.FIDCARD                                       ";
						sql +="            AND C.KINDCODE = D.KINDCODE                                     ";
						sql +="            AND C.ITEMCODE = D.ITEMCODE                                     ";
						sql +="            AND (C.SETTLEAREA > D.INSUREAREA OR C.SETTLESUM > D.SUMAMOUNT)) ";

					}
					else if( plantingFarmerListFlag.indexOf(strRiskCode) > -1)
					{
						sql +=" SELECT COUNT(c.settlelistcode) AS RESULT                                                               ";
						sql +="   FROM PLANTINGSETTLELIST C                                              ";
						sql +="  WHERE C.SETTLELISTCODE = '"+ prpLcompensateDto.getClaimRelationNo()+    "'";
						sql +="    AND NODETYPE = 'compe'                                                  ";
						sql +="    AND EXISTS                                                              ";
						sql +="  (SELECT 1                                                                 ";
						sql +="           FROM PLANTINGPOLICYLIST D                                      ";
						sql +=" WHERE D.INUSRELISTCODE = '"+ blPrpCmainAgri.getArr(0).getRelationListNo()+    "'";
						sql +="            AND C.fcode = D.fcode                                       ";
						sql +="            AND C.KINDCODE = D.KINDCODE                                     ";
						sql +="            AND (C.SETTLEAREA > D.INSUREAREA OR C.SETTLESUM > D.SUMAMOUNT)) ";


					}
					if(!sql.equals(""))
					{
						DBManager dbManager = new DBManager();
						ResultSet rs = null;
						//String strResult = "";
						int count = 0 ;
						try{
							dbManager.open("NXDADataSource");
							dbManager.beginTransaction();
							rs = dbManager.executeQuery(sql);
							dbManager.commitTransaction();
							while(rs.next())
							{
								result = rs.getString("result");

								count++;
								if(result == null){
									result = "0";
								}


							}

						}

						finally{
							if(rs!=null){
								rs.close();
							}
							if(dbManager!=null){
								dbManager.close();
							}
						}
					}else
						result = "-1";
				}
			}catch (Exception e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		} 
		return result;
	}

}