<script language="Javascript" src="/claim/common/js/Common.js" ></script>
<script language="Javascript" src="/claim/common/js/MulLine.js" ></script>
<script language="Javascript" src="/claim/common/js/ValidateData.js" ></script>
<script language="Javascript" src="/claim/common/js/Validate.js" ></script>
<script language="Javascript" src="/claim/common/js/InputCode.js" ></script>
<script language="Javascript" src="/claim/common/js/Application.js" ></script>
<script language="Javascript" src="/claim/common/js/ClaimPub.js" ></script>
<script language="Javascript" src="/claim/common/js/jquery-1.4.2.min.js" ></script>    
<script language="Javascript" src="/claim/common/js/formUtil.js" ></script>